AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Sample Application
Resources:
  MyLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://node-lambda-sample-uttne/a66c19724c597074052aed6de7be7efc
      Handler: index.handler
      Runtime: nodejs18.x
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /api
            Method: get
    Metadata:
      SamResourceId: MyLambdaFunction
